### ISSUE TITLE
Hledání náhrady

### ISSUE THREAD

**Issue by ChroustJan** [mlab-modules/ALTIMET01#3]
Skončila životnost senzoru [MPL3115A2](https://www.nxp.com/docs/en/data-sheet/MPL3115A2.pdf) .

NXP snad bude dál vyrábět tento IO: 

- [FXPS7115D4](https://www.nxp.com/docs/en/data-sheet/FXPS7115D4.pdf) - špatná dostupnost, horší parametry.
- [BMP390](https://www.bosch-sensortec.com/products/environmental-sensors/pressure-sensors/bmp390/)
- [DPS310](https://www.infineon.com/cms/en/product/sensor/pressure-sensors/pressure-sensors-for-iot/dps310/) 

Podobná konstrukce tomu co jsme měli: [MS5611](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS5611-01BA03%7FB3%7Fpdf%7FEnglish%7FENG_DS_MS5611-01BA03_B3.pdf%7FCAT-BLPS0036) mají i levnější méně přesné provedení. Zatím mi značka te.com přijde nejblíže tomu co potřebujeme.

**Comment by kaklik** [comment]
Ten MS5611 se nyní používá i v [nových autopilotech](https://docs.px4.io/master/en/flight_controller/cuav_x7.html) a měřil i výšku balonu FIK-5 a FIK-6. Takže je to zřejmě dobrá náhrada.

**Comment by ChroustJan** [comment]
@kaklik a dá se zjistit jakou verzi tam použili? Ale možná pro nás bude nejlepší ta nejpřesnější. Ale myslím, že mají snad všechny jedno pouzdro. Takže by to pak na návrh nemělo případně vliv.

**Comment by kaklik** [comment]
> @kaklik a dá se zjistit jakou verzi tam použili? Ale možná pro nás bude nejlepší ta nejpřesnější. Ale myslím, že mají snad všechny jedno pouzdro. Takže by to pak na návrh nemělo případně vliv.

Nenapadá mě žádný jasný postup, jak to zjistit. Zároveň nějak ani v datasheetu nevidím, že by existovaly nějaké odlišné verze. V linku na datasheet v komentáři je jen jedno typové označení.

**Comment by kaklik** [comment]
Další možnou náhradou je [SPL06](https://datasheet.lcsc.com/lcsc/2101201914_Goertek-SPL06-001_C2684428.pdf)

**Comment by roman-dvorak** [comment]
Vznikl [ALTIMET02](https://github.com/mlab-modules/ALTIMET02) se senzorem [MS561101BA03](https://www.te.com/usa-en/product-MS561101BA03-50.html)
